config/routes.rb
Rails.application.routes.draw do


    root to: 'homes#top'
   resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @book = Book.all
  end

  def create
      book = Book.new(book_params)
      book.save
      redirect_to booker_path(book.id)
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to bookers_path
  end

    private
  # ストロングパラメータ
  def book_params
    params.permit(:title, :body)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
      @book = Book.new(book_params)
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
     else
       @books = Book.all
       render:index
      end
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    #book = Book.find(params[:id])
    #book.update(book_params)
    #redirect_to book_path(book)

     @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
     else
       render:edit
     end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

    private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/bookers/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:booke_path(@book), local:true do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "show", edit_book_path(@book) %>
<%= link_to "back", books_path %>

app/views/bookers/index.html.erb
<h1>Books</h1>
<table>
  <thead>
  　<tr>
    　<th>Title</th>
    　<th>Body</th>
    　<th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
     <% @book.each do |book| %>
    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to "show", books_path(book) %></td>
     <td><%= link_to "edit", edit_bookspath(book) %></td>
     <td><%= link_to "delete", books_path(book), method: :delete %></td>
   </tr>
   <% end %>
  </tbody>

</table>


<h1>NEW BOOK</h1>
<!-- form_with部分 -->
<%= form_with model:@book, url:'/books',local:true do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit 'create Book' %>

<% end %>

app/views/bookers/new.html.erb
<h1>Bookers#new</h1>
<p>Find me in app/views/bookers/new.html.erb</p>

app/views/bookers/show.html.erb
<h2>タイトル</h2>
<p><%= @book.title %></p>
<h2>本文</h2>
<p><%= @book.body %></p>

<%= link_to "edit", edit_books_path(@book) %>
<%= link_to "back", books_path %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@book, url:book_path(@book), local:true do |f| %>

  <h5>Title</h5>
  <%= f.text_field :title %>

  <h5>Body</h5>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h2>Books</h2>
<table>
  <thead>
  　<tr>
    　<th>Title</th>
    　<th>Body</th>
    　<th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
     <% @books.each do |book| %>
    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to "Show", book_path(book) %></td>
     <td><%= link_to "Edit", edit_book_path(book) %></td>
     <td><%= link_to "Destroy", book_path(book), method: :delete , data: { confirm: 'Are you sure？' } %></td>
   </tr>
   <% end %>
  </tbody>


</table>


<h2>New book</h2>

  <% if @book.errors.any?%>
  <%= @book.errors.count %>errors prohibited this book from being saved:

  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<!-- form_with部分 -->
<%= form_with model:@book, url:'/books',local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
<% end %>

<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>


<%= link_to "start", books_path %>

app/views/index/edit.html.erb
<h1>Index#edit</h1>
<p>Find me in app/views/index/edit.html.erb</p>

app/views/index/show.html.erb
<h1>Index#show</h1>
<p>Find me in app/views/index/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>